### ISSUE TITLE
Swift Package Manager manifest issue in Xcode 13.3

### ISSUE THREAD

**Issue by fiserjCN** [uxcam/ios-swiftui#1]
When I try to install the package using Swift Package Manager and new Xcode 13.3, I get the following error while resolving package versions:

> invalidManifestFormat("Missing or empty JSON output from manifest compilation for ios-swiftui")

I can reproduce the error even if I clone the repository and run `swift package dump-package` or `swift build` locally.

**Comment by BibekUXCam** [comment]
Hi @fiserjCN it seems to be the issue with Xcode 13.3.
We have a new update. Please check it out.

**Comment by fiserjCN** [comment]
Works like a charm, thank you!
