### ISSUE TITLE
Duplicate symbols for architecture

### ISSUE THREAD

**Issue by renatosmf** [uxcam/ios-swiftui#9]
Hello Guys, 

We've been facing this error:  "Duplicate symbols for architecture arm64" related to PLCrashReporter dependency. We believe that your framework has embedded the PLCrashReporter classes instead of declare as an external dependency in your dependency manager, what's not recommended.

**Comment by ankit-uxcam** [comment]
Hey @renatosmf, thank you for reporting this issue. We have already fixed this issue in latest UXCam (native UXCam and not UXCamSwiftUI) release (v3.5.3), so please update it to v3.5.3 and it should be fixed. If you are using cocoapods, you can do it by `pod update UXCam`

**Comment by saviosailas** [comment]
@ankit-uxcam @uxcam-mobile Is it possible to mask SwiftUI view using UXCam?
